spring.application.name=tienda
#Se define el puerto por el que escuha el servidor web
server.port=80

#Se define el formato de hora del log de la consola
logging.pattern.dateformat=hh:mm

#Se evita el mensaje de Spring en banner
spring.main.banner-mode=off

#Se evita el uso de cache en desarrollo, luego en produccion si
spring.thymeleaf.cache=false

#Conexión local a la BD macrobiotica en MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/macrobiotica

#Usuario y clave de creaTablas.sql
spring.datasource.username=usuario_prueba
spring.datasource.password=Usuar1o_Clave.

#Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

#Esta información se utiliza para obtener acceso a su storage.
firebase.bucket.name=techshop-1e6d4.firebasestorage.app
firebase.storage.path=ojose38936
firebase.json.path=firebase
firebase.json.file=techshop-1e6d4-firebase-adminsdk-fbsvc-64840c7434.json
